// Generated by injectable_generator; do not edit.
import 'package:flutter_application_1/core/di/injection.config.dart';
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

final GetIt getIt = GetIt.instance;

@InjectableInit(asExtension: false)
void configureDependencies({String env = Environment.dev}) =>
    init(getIt, environment: env);
