# STABLE: Repository port. FastCRUD satisfies this Protocol structurally.
from typing import Any, Protocol


class IRepository(Protocol):
    async def get(self, db: Any, **kwargs: Any) -> dict | None: ...
    async def get_multi(self, db: Any, **kwargs: Any) -> dict: ...
    async def create(self, db: Any, object: Any, **kwargs: Any) -> dict | None: ...
    async def update(self, db: Any, object: Any, **kwargs: Any) -> None: ...
    async def delete(self, db: Any, **kwargs: Any) -> None: ...
    async def exists(self, db: Any, **kwargs: Any) -> bool: ...
